server:
  port: 8100
spring:
  application:
    name: book-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    '[org.apache.zookeeper.ClientCnxn]': WARN