server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cambio-db:3306/cambio_service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&enabledTLSProtocols=TLSv1.2
    username: root
    password: admin123
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://cambio-db:3306/cambio_service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&enabledTLSProtocols=TLSv1.2
    user: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sleuth:
    sampler:
      probability: 1.0
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs