---
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/leandrocgsi/config-server/
          uri: https://github.com/leandrocgsi/erudio-config-server
          # username: username
          # password: password
          default-label: main
          search-paths:
          - 'greeting-service*'
          - 'naming-server*'
          - 'api-gateway*'
          - 'cambio-service*'
          - 'book-service*'