name: Continuous Integration with Github Actions

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'

    - name: Build Eureka Naming Server Container Image
      working-directory: ./Dockerizing/08-naming-server
      run: mvn spring-boot:build-image -DskipTests
    
    - name: Build API Gateway Container Image
      working-directory: ./Dockerizing/08-api-gateway
      run: mvn spring-boot:build-image -DskipTests
    
    - name: Build Cambio Microsservice Jar
      working-directory: ./Dockerizing/08-cambio-service
      run: mvn clean package -DskipTests

    - name: Build Book Microsservice Jar
      working-directory: ./Dockerizing/08-book-service
      run: mvn clean package -DskipTests
 
    - name: Docker Compose Build
      working-directory: ./Dockerizing
      run: docker-compose build

    - name: Push Docker images
      uses: docker/build-push-action@v2.5.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/book-service
        tag_with_ref: true
