name: Continuous Integration with Github Actions

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: action-maven
      uses: comchangs/action-maven@v0.4-beta

    - name: Build Eureka Naming Server Container Image
      working-directory: ./Dockerizing/08-naming-server
      run: mvn spring-boot:build-image -DskipTests
    
    - name: Build API Gateway Container Image
      working-directory: ./Dockerizing/08-api-gateway
      run: mvn spring-boot:build-image -DskipTests
    
    - name: Build Cambio Microsservice Jar
      working-directory: ./Dockerizing/08-cambio-service
      run: mvn clean package -DskipTests

    - name: Build Book Microsservice Jar
      working-directory: ./Dockerizing/08-book-service
      run: mvn clean package -DskipTests
 
    - name: Docker Compose Build
      working-directory: ./Dockerizing
      run: docker-compose build
      
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | winpty docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
